### ISSUE TITLE
Making pandas optional

### ISSUE THREAD

**Issue by gthomas-slack** [acroz/pylivy#66]
Thanks for creating this library, it is super useful!

For my use-case pandas is unnecessary, as I end up needing to convert the pandas dataframe immediately back into a Dict. I've got a fork over here where I've made pandas optional for the `read_sql` method:  https://github.com/acroz/pylivy/compare/master...gthomas-slack:make-pandas-optional

Wondering if this is something you would accept to be merged into this library, and if so, what tests would you want added?

Thanks!

**Comment by acroz** [comment]
Thanks for this suggestion @gthomas-slack.

Is it the fact that you find yourself converting back to a dictionary the motivation for this, or that you are forced to install pandas as a dependency?

If it's the former, I do prefer having the API return the more structured DataFrame object rather than a dictionary whose structure is not reported to the user. It's also nice to have symmetry with the `read` method, which unfortunately has to work in a completely different way.

If you'd like to avoid installing pandas, this seems like a good objective. However, I'm struggling to find a good way of making this dependency optional but still have it installed by default.

**Comment by traviscook21** [comment]
100% agree that having the API return an object that includes metadata about the structure of the underlying data seems like a good goal to have.  However, it does appear like the structure of the data does appear in the underlying dictionary: https://github.com/acroz/pylivy/blob/master/livy/session.py#L56-L58

I'm wondering if it makes sense to include `pandas` as an optional dependency in `extras` and then wrap the import:
```
try:
     import pandas
     USE_PANDAS = true
except ImportError:
     USE_PANDAS = false
```

This seems like it solves most of the concerns other than "still have it installed by default".  As far as I can tell, the suggestion seems to be a post install hook inside of `setup.py` that will install the `pandas` extra after the initial installation, but this doesn't appear to work with wheels.  In addition, it'll be tricky to figure out how to allow people to specify they don't want pandas since that hook will run as part of any install process.

https://stackoverflow.com/questions/53376135/install-by-default-optional-dependencies-in-python-setuptools

**Comment by gthomas-slack** [comment]
To provide a little bit more context, the motivation is less around not having to have `pandas` as a dependency (though I guess this would also be nice if it's not being used), and more around having to convert back to a dictionary for our particular use case. For our use-case what is returned from Livy is pretty much the exact format that we already need.

The other motivation is that by converting to and returning the pandas dataframe, we lose the context of the original Hive/Spark data types, and it's not straight forward to infer from the datatypes in the pandas dataframe.

**Comment by gthomas-slack** [comment]
Closing this,  as the `Statement` model already returns the json structured data that we ideally want to use, so for our use-case we can just use statements with `statement_get()` instead of `read_sql()`

**Comment by quartox** [comment]
One note I will add is that the pandas dependency prevented us from using pylivy on aws lambda. The goal was to run short batch jobs via livy that did not return any serialized result. We switched to using a long-running spark structured streaming job, but wanted to mention that there are other reasons to remove a mandatory pandas dependency.
